<$PLAN9/src/mkhdr 

LIB=libauthsrv.$O.a

OFILES=\
	authpak.$O\
	passtokey.$O\
	form1.$O\
	hkdf_x_plan9.$O\
#	_asgetticket.$O\
#	_asrdresp.$O\
#	convA2M.$O\
#	convM2A.$O\
#	convM2PR.$O\
#	convM2T.$O\
#	convM2TR.$O\
#	convPR2M.$O\
#	convT2M.$O\
#	convTR2M.$O\
#	nvcsum.$O\
#	readcons.$O\
#	_asgetpakkey.$O\
#	_asgetresp.$O\
#	_asrequest.$O\
	
<$PLAN9/src/mklib

clean:V:
	rm -f *.[$OS] $LIB