LIB=libc9.$O.a 

default:V: $LIB

OFILES=\
    c9.$O\
    x9fs.$O


$O.*:V:
    clang -std=c99 -fms-extensions -DC9_NO_CLIENT -O0 -g -Wall -Wextra -Wshadow -c *.c 

$LIB: $O.*
	ar -rv $LIB *.o

all install:V: $LIB

clean:V:
    rm -f $LIB *.[$OS]
